#ifndef HLPLAYER_AES_CTR_256_H
#define HLPLAYER_AES_CTR_256_H

#include <cstddef>
#include <cstdint>

#include "CryptoExport.h"

struct AVAES;

namespace hlplayer::crypto {

/// AES-256-CTR stream cipher built on FFmpeg's av_aes (ECB mode).
///
/// Counter block layout (16 bytes): nonce[12] || counter[4] (big-endian).
/// Keystream is generated by ECB-encrypting each counter block, then XORed
/// with plaintext/ciphertext. Counter increments after each block.
class HLPLAYER_CRYPTO_API AesCtr256 {
public:
    AesCtr256();
    ~AesCtr256();

    // Non-copyable, movable
    AesCtr256(const AesCtr256&) = delete;
    AesCtr256& operator=(const AesCtr256&) = delete;
    AesCtr256(AesCtr256&& other) noexcept;
    AesCtr256& operator=(AesCtr256&& other) noexcept;

    /// Initialize with 32-byte key and 12-byte nonce.
    /// Returns true on success.
    bool init(const uint8_t key[32], const uint8_t nonce[12]);

    /// Encrypt/decrypt data in-place safe. Same operation for CTR mode.
    /// Advances internal counter state.
    void process(const uint8_t* input, uint8_t* output, size_t length);

    /// Seek to absolute byte offset. Resets counter and discards leading
    /// keystream bytes.
    void seek(uint64_t absoluteOffset);

private:
    struct AVAES* m_aesCtx;
    uint8_t m_nonce[12];
    uint32_t m_counter;
    uint8_t m_keystream[16];
    int m_keystreamPos;
    bool m_initialized;

    /// Encrypt counter block into m_keystream, then increment counter.
    void generateKeystreamBlock();

    /// Helper: convert uint32_t to 4 big-endian bytes
    static void uint32ToBe(uint32_t val, uint8_t out[4]);
};

} // namespace hlplayer::crypto

#endif // HLPLAYER_AES_CTR_256_H
